/* Monthly workbench. Every business mutation goes through the local API. */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={month:'',view:'overview',data:null,months:[],incomeFilter:'all',receiptFilter:'included',search:'',entity:'',page:1,detail:null};
const titles={overview:'月度概览',income:'收入入账',receipts:'回款填写',sources:'本月资料',history:'处理记录'};
const labels={ready:'待在UO操作',review:'待核实',done:'系统已同步',harmony:'鸿蒙仅核开票',scope:'范围待核实',included:'会写入回款表',excluded:'不写入回款表',proposed:'建议写入'};
const reviewLabel=r=>r.candidates?.length?"候选待确认":r.reviewType==="missing"?"缺少系统资料":r.reviewType==="difference"?"金额差异":labels[r.status];
const roleNames={invoice:'实际发票',application:'开票申请',system:'UO收入明细',bank:'银行原始流水',template:'回款底稿'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null?'—':(v/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const badge=(text,color='')=>`<span class="badge ${color}">${esc(text)}</span>`;
const button=(text,action,cls='')=>`<button class="btn ${cls}" data-action="${action}">${text}</button>`;
const monthLabel=m=>`${m.slice(0,4)}年${Number(m.slice(5))}月`;
const src=s=>`<a href="/api/sources/${esc(s.id)}" download>${esc(s.file)} · ${esc(s.sheet)} · 第${s.row}行 ↗</a>`;
let toastTimer,loadSequence=0;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500)}
async function api(url,options={}){const r=await fetch(url,options);let data;try{data=await r.json()}catch{throw new Error('本地服务响应异常')}if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:'操作未完成，请检查资料类型及格式');return data}
async function perform(fn){$('#error').hidden=true;try{return await fn()}catch(e){$('#error').textContent=e.message;$('#error').hidden=false;toast(e.message);return null}}
async function load(month=state.month){const sequence=++loadSequence;return await perform(async()=>{const data=await api(`/api/months/${month}`);if(sequence!==loadSequence)return false;state.month=month;state.data=data;state.page=1;render();history.replaceState(null,'',`/?month=${month}&view=${state.view}`);return true})}
function navigate(view){state.view=view;state.search='';state.entity='';state.page=1;render();history.replaceState(null,'',`/?month=${state.month}&view=${view}`)}
const sourceCount=(role)=>state.data.sources.filter(s=>s.role===role).length;
function title(subtitle,actions=''){return `<div class="title-row"><div><span class="eyebrow">MONTHLY OPERATIONS / ${state.month.replace('-','.')}</span><h1>${state.view==='overview'?monthLabel(state.month)+' 工作概览':titles[state.view]}</h1><p class="subtitle">${subtitle}</p></div><div class="actions">${actions}</div></div>`}
function exportsHTML(){const rows=state.data.exports.filter(e=>e.current);return rows.length?rows.map(e=>`<div class="delivery-row"><div class="file-icon">XLSX</div><div><h4>${esc(e.kind==='income'?'收入操作清单':'回款填写结果')}</h4><p>${esc(e.name)} · ${e.created_at.slice(11,16)}</p></div><a href="/api/exports/${e.id}" download>下载 ↗</a></div>`).join(''):`<div class="empty">处理结果可在对应页面生成 Excel。<br>生成的文件会保留在这里。</div>`}
function overview(){const d=state.data,i=d.income,r=d.receipts,hasInvoice=sourceCount('invoice')>0,hasBank=sourceCount('bank')>0,incStats=i.stats,rc=r.stats,issues=[];
  if(!hasInvoice)issues.push(['本月实际发票尚未提供','收入清单需要本月实际发票；已有7月发票会保留在7月。','sources']);
  if(!r.template)issues.push(['尚未指定本月回款底稿','先选择实际要填写的工作簿，再生成回款副本。','sources']);
  if(incStats.review)issues.push([`${incStats.review}组收入需要核实`,'查看发票、申请与系统明细，确认账期或差额。','income']);
  if(rc.review||rc.proposed)issues.push([`${(rc.review||0)+(rc.proposed||0)}笔其他来款尚未纳入`,'这部分不计入已纳入金额；可按银行摘要逐笔确认。','receipts']);
  return title('本月的收入入账与回款填写，放在一起检查和交付。',button('↻ 重新检查','run'))+
  `<div class="period-strip"><strong>两项月度工作</strong><span>收入入账 ${badge(hasInvoice?'已读取发票':'缺少实际发票',hasInvoice?'blue':'amber')}</span><span>回款填写 ${badge(r.template?'已读取底稿':'缺少底稿',r.template?'green':'amber')}</span><span class="quiet">按实际开票月与到账月归档</span></div>
  <div class="workflow-grid"><section class="card"><div class="card-head"><div class="section-icon"><span class="tile-icon">▤</span><h2>收入入账</h2></div>${badge(hasInvoice?'已生成核对结果':'资料待补充',hasInvoice?'blue':'amber')}</div>
  ${hasInvoice?`<div class="card-number">${i.inScopeCount}<span>张渠道发票</span></div><div class="card-caption">含税发票金额 ¥ ${money(i.inScopeAmountCents)}</div><div class="mini-stats"><div><b>${i.pendingCount}</b><span>待在 UO 操作</span></div><div><b>${incStats.review||0}</b><span>对应待核实</span></div><div><b>${incStats.done||0}</b><span>系统已同步</span></div></div>`:`<div class="card-number empty-number">等待本月发票</div><div class="card-caption">当前没有 ${monthLabel(state.month)} 的实际发票导出</div><div class="empty-work">收到实际发票后，按公司和渠道<br>找到对应收入，再核对系统同步状态。</div>`}
  <div class="card-foot"><p>发票 → 公司与渠道 → 收入账期</p>${button(hasInvoice?'查看收入清单 →':'查看本月资料 →',hasInvoice?'income':'sources','small')}</div></section>
  <section class="card"><div class="card-head"><div class="section-icon"><span class="tile-icon">↙</span><h2>回款填写</h2></div>${badge(r.template?'已载入现有回款':'待检查纳入范围',r.template?'green':'amber')}</div>
  <div class="card-number money-hero">${hasBank?money(r.amountCents):'—'}<span>元</span></div><div class="card-caption">${state.month} 本次回款表金额 · 人民币</div><div class="mini-stats"><div><b>${rc.included||0}</b><span>会写入笔数</span></div><div><b>${r.entityTotals['芜湖享游'].count}</b><span>芜湖享游</span></div><div><b>${r.entityTotals['上海幻电'].count}</b><span>上海幻电</span></div></div>
  <div class="card-foot"><p>只填写回款页<br>后续工作表由你核对</p>${button('查看回款结果 →','receipts','small')}</div></section></div>
  <div class="overview-bottom"><section class="card"><div class="list-header"><h3>接下来检查</h3><span class="quiet">${issues.length}项提示</span></div>${issues.map(([t,p,v])=>`<div class="attention"><span class="attention-mark">!</span><div><b>${t}</b><p>${p}</p></div><button class="text-btn" data-action="${v}">查看 →</button></div>`).join('')||'<div class="empty">当前没有资料缺口提示。</div>'}</section>
  <section class="card"><div class="list-header"><h3>本月交付文件</h3><button class="text-btn" data-action="history">处理记录 →</button></div>${exportsHTML()}<p class="scope-text">输出保留版本。更换资料或确认范围后，旧文件仍可在处理记录里查到。</p></section></div>
  ${state.month==='2026-08'&&state.months.includes('2026-07')?'<div class="split-note"><span>已有7月实际发票，可切换查看收入核对结果。</span><button class="text-btn" data-action="july">查看7月收入 →</button></div>':''}`;
}
function toolsHTML(kind,filters){return `<div class="panel-tools"><div class="tabs">${filters.map(([v,t])=>`<button class="tab ${(kind==='income'?state.incomeFilter:state.receiptFilter)===v?'active':''}" data-filter="${v}">${t}</button>`).join('')}</div><div class="filter-tools"><select id="entityFilter" aria-label="筛选主体"><option value="">全部主体</option>${['芜湖享游','上海幻电'].map(e=>`<option ${state.entity===e?'selected':''}>${e}</option>`).join('')}</select><input id="search" type="search" placeholder="搜索公司、金额或说明" aria-label="搜索记录" value="${esc(state.search)}"></div></div>`}
function incomeView(){const i=state.data.income;return title('从实际发票出发，查看对应的公司、渠道、收入月份与系统状态。',button('生成收入 Excel','export-income','primary'))+
  (!sourceCount('invoice')?`<section class="card"><div class="empty"><strong>本月实际发票尚未提供</strong>当前其他月份的发票不会计入 ${monthLabel(state.month)}。<br><br>${button('查看资料','sources')}</div></section>`:
  `<div class="summary-line"><span><b>${i.inScopeCount}</b>张渠道发票</span><span><b>¥ ${money(i.inScopeAmountCents)}</b>含税金额</span><span>另${i.scopeReviewCount}张范围待核实</span></div>
  <div class="notice neutral">实际开票月份为 ${state.month}。收入月份来自发票备注、申请或人工确认；金额候选会明确列出，不直接当作账期已确认。</div>
  <section class="panel">${toolsHTML('income',[['all','全部'],['ready','待操作'],['review','待核实'],['done','已同步'],['harmony','鸿蒙'],['scope','范围待核实']])}<div id="tableArea"></div></section>
  <p class="scope-text">共读取 ${i.rawInvoiceCount} 张实际发票，${i.skipped['玩家及非渠道发票']||0} 张玩家及非渠道发票未进入本工作清单。未在申请中出现的其他公司保留为范围待核实。</p>`)}
function receiptView(){const r=state.data.receipts;return title('“会写入回款表”表示生成Excel时会填到回款Sheet；不代表已核销或已在UO入账。',button('生成回款 Excel','export-receipt','primary'))+
  `<div class="summary-line"><span><b>${r.stats.included||0}</b>笔会写入回款表</span><span><b>¥ ${money(r.amountCents)}</b>人民币</span><span>重复交易 ${r.duplicateCount}笔</span></div>
  ${r.template?`<div class="notice neutral">当前底稿：<strong>${esc(r.template.name)}</strong>。${r.existingCount}笔现有回款已找到银行来源；生成时保留其他工作表。</div>`:'<div class="notice">本月尚未指定回款底稿。已读取流水，可先检查范围；指定底稿后才能生成填写结果。</div>'}
  ${r.unmatchedTemplateCount?`<div class="notice">底稿中有${r.unmatchedTemplateCount}笔未找到本月银行来源，暂不生成替换副本。</div>`:''}
  <section class="panel">${toolsHTML('receipt',[['included',`会写入 ${r.stats.included||0}`],['pending',`待检查 ${(r.stats.review||0)+(r.stats.proposed||0)}`],['excluded',`不写入 ${r.stats.excluded||0}`],['all','全部收入流水']])}<div id="tableArea"></div></section>
  <p class="scope-text">外币分别显示，不与人民币相加。纳入确认只作用于本月这一笔交易；不推断业务月份或扣减应收。</p>`}
function tableRender(){const isIncome=state.view==='income';if(!$('#tableArea'))return;const all=isIncome?state.data.income.cases:state.data.receipts.rows;
  const filter=isIncome?state.incomeFilter:state.receiptFilter;
  const rows=all.filter(r=>(filter==='all'||filter==='pending'?filter==='all'||['review','proposed'].includes(r.status):r.status===filter)&&(!state.entity||r.entity===state.entity)&&(!state.search||JSON.stringify(r).toLowerCase().includes(state.search.toLowerCase())||money(r.amountCents).replaceAll(',','').includes(state.search)));
  const size=25,pages=Math.max(1,Math.ceil(rows.length/size));state.page=Math.min(state.page,pages);const visible=rows.slice((state.page-1)*size,state.page*size);
  const head=isIncome?'<th>公司 / 主体</th><th>渠道与收入账期</th><th class="money">含税金额（元）</th><th>状态</th><th>下一步</th><th></th>':'<th>付款方 / 主体</th><th>到账日期</th><th class="money">金额</th><th>是否写入回款表</th><th>依据</th><th></th>';
  $('#tableArea').innerHTML=`<div class="table-wrap"><table><thead><tr>${head}</tr></thead><tbody>${visible.map(r=>`<tr><td class="company-cell"><strong>${esc(r.company||r.payer||'付款方未提供')}</strong><div class="cell-sub">${esc(r.entity)}${isIncome?` · ${r.invoices.length}张发票`:''}</div></td><td>${isIncome?`${esc(r.channel)}<div class="cell-sub">${r.months.length?esc(r.months.join('、')):(r.candidates?.length===1?r.candidates[0].month+'（候选）':'账期待核实')}</div>`:esc(r.date)}</td><td class="money">${money(r.amountCents)}${!isIncome?`<div class="cell-sub">${esc(r.currency)}</div>`:''}</td><td>${badge(r.localDone?'本地已记录完成':reviewLabel(r),['included','done'].includes(r.status)?'green':r.status==='review'||r.status==='proposed'?'amber':r.status==='excluded'?'':'blue')}${r.staleDecision?'<div class="cell-sub">资料变更，请重新确认</div>':''}</td><td class="reason-cell">${esc(isIncome?(r.candidates?.length?`找到${r.candidates.length}个金额候选，待确认账期`:r.reason||r.action):r.reason)}</td><td><button class="text-btn" data-detail="${r.id}">查看依据 →</button></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">当前筛选下没有记录</div></td></tr>'}</tbody></table></div><div class="table-footer"><span>共${rows.length}条 · 第${state.page}/${pages}页</span><div class="actions"><button class="btn small" data-action="prev" ${state.page===1?'disabled':''}>上一页</button><button class="btn small" data-action="next" ${state.page===pages?'disabled':''}>下一页</button></div></div>`;
}
function sourceView(){return title('每份资料保存独立副本，实际日期和用途分别记录。')+
  `<div class="source-grid">${Object.entries(roleNames).map(([role,name])=>`<section class="card source-card"><div class="list-header"><h3>${name}</h3>${badge(sourceCount(role)?`${sourceCount(role)}份`:'尚未提供',sourceCount(role)?'':'amber')}</div>${state.data.sources.filter(s=>s.role===role).map(s=>`<div class="source-item"><div class="file-icon">XLSX</div><div class="info"><strong>${esc(s.name)}</strong><p>${esc(s.entity||'共用资料')} · ${s.rows}行${JSON.parse(s.months).length?` · ${esc(JSON.parse(s.months)[0])} 至 ${esc(JSON.parse(s.months).at(-1))}`:''}</p><p>来源：${esc(s.origin)}</p><a class="quiet" href="/api/sources/${s.id}" download>下载来源副本 ↗</a></div><button data-remove="${s.id}">移出本月</button></div>`).join('')||'<p class="scope-text">收到此类资料后，上传到下方即可继续。</p>'}</section>`).join('')}</div>
  <section class="card upload-card"><h3>添加本月或新月份资料</h3><p class="scope-text">选择资料用途与主体。系统导出、开票申请会替换本月同类版本；原始资料副本和历史结果保留。</p><form id="uploadForm" class="upload-form"><div class="field"><label for="uploadMonth">处理月份</label><input id="uploadMonth" name="month" type="month" value="${state.month}" required></div><div class="field"><label for="uploadRole">资料用途</label><select id="uploadRole" name="role">${Object.entries(roleNames).map(([r,n])=>`<option value="${r}">${n}</option>`).join('')}</select></div><div class="field"><label for="uploadEntity">主体</label><select id="uploadEntity" name="entity"><option>上海幻电</option><option>芜湖享游</option><option value="">共用资料</option></select></div><div class="field"><label for="uploadFile">Excel文件</label><input id="uploadFile" name="file" type="file" accept=".xlsx" required></div><button class="btn primary" type="submit">添加并检查</button></form></section>`}
function historyView(){return title('查看本月生成的文件、资料变更及人工确认。',`<a class="btn" href="/api/backup" download>备份处理记录</a>`)+`<section class="card"><div class="list-header"><h3>已生成文件</h3><span class="quiet">${state.data.exports.length}个版本</span></div>${state.data.exports.map(e=>`<div class="delivery-row ${e.current?'':'stale'}"><div class="file-icon">XLSX</div><div><h4>${esc(e.name)} ${e.current?badge('当前版本','green'):badge('历史版本')}</h4><p>${e.created_at.replace('T',' ').slice(0,19)} · ${e.kind==='receipt'?'其他工作表保留检查已通过':'按原始发票重新核对'}</p></div><a href="/api/exports/${e.id}" download>下载 ↗</a></div>`).join('')||'<div class="empty">暂无生成文件</div>'}</section><section class="card section-space"><h3>处理记录</h3>${state.data.events.map(e=>`<div class="event"><div class="event-time">${e.time.replace('T',' ').slice(0,19)}</div><div><strong>${esc(e.action)}</strong><p>${esc(e.detail)}</p></div></div>`).join('')}</section>`}
function render(){if(!state.data)return;$('#breadcrumb').textContent=titles[state.view];$('#savedAt').textContent=`结果更新 ${state.data.builtAt.slice(5,16).replace('T',' ')} · 已保存`;
  $('#navIncome').textContent=state.data.income.invoiceCount||'';$('#navReceipt').textContent=state.data.receipts.stats.included||'';
  $$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===state.view));$('#monthSelect').value=state.month;
  $('#content').innerHTML=({overview,income:incomeView,receipts:receiptView,sources:sourceView,history:historyView})[state.view]();tableRender();
  if($('#search'))$('#search').addEventListener('input',e=>{state.search=e.target.value;state.page=1;tableRender()});
  if($('#entityFilter'))$('#entityFilter').addEventListener('change',e=>{state.entity=e.target.value;state.page=1;tableRender()});
  if($('#uploadForm'))$('#uploadForm').addEventListener('submit',upload);
}
function openDetail(id){const isIncome=state.view==='income',r=(isIncome?state.data.income.cases:state.data.receipts.rows).find(r=>r.id===id);if(!r)return;state.detail={id,kind:isIncome?'income':'receipt'};
  $('#drawerEyebrow').textContent=isIncome?'INVOICE & INCOME':'BANK RECEIPT';$('#drawerTitle').textContent=r.company||r.payer||'付款方未提供';
  let html=`<section class="drawer-section"><div class="drawer-facts"><div><label>${isIncome?'含税发票金额':'银行到账金额'}</label><strong>${isIncome?'CNY':esc(r.currency)} ${money(r.amountCents)}</strong></div><div><label>主体</label><strong>${esc(r.entity)}</strong></div><div><label>${isIncome?'收入账期':'到账日期'}</label><strong>${isIncome?esc(r.months.join('、')||'待核实'):r.date}</strong></div><div><label>当前状态</label>${badge(r.localDone?'本地已完成':reviewLabel(r),r.status==='review'?'amber':'blue')}</div></div></section>`;
  if(isIncome){
    if(r.reason)html+=`<section class="drawer-section"><div class="notice">${esc(r.reason)}</div>${r.candidates?.map(c=>`<div class="evidence-card"><p><strong>金额候选：${c.month}</strong> · ${esc(c.games.join('、'))}</p><p>${esc(c.note)}</p>${c.systems.map(s=>`<p>${esc(s.game)} · ${money(s.amountCents)}元 · ${esc(s.syncStatus)}<br>${src(s.source)}</p>`).join('')}<button class="btn small" data-candidate="${c.month}">我确认对应 ${c.month}</button></div>`).join('')||''}</section>`;
    html+=`<section class="drawer-section"><h3>实际发票 · ${r.invoices.length}张</h3>${r.invoices.map(i=>`<div class="evidence-card"><p><strong>${esc(i.no)}</strong></p><p>${i.date} · ¥ ${money(i.amountCents)} · ${esc(i.invoiceState)}</p>${i.remark?`<p>原始备注：${esc(i.remark)}</p>`:''}${src(i.source)}</div>`).join('')}</section>`;
    html+=`<section class="drawer-section"><h3>开票申请依据</h3>${r.applications.map(a=>`<div class="evidence-card"><p>${esc(a.channel)} · ${esc(a.periodText)} · ¥ ${money(a.amountCents)}</p><p>${esc(a.gamesText)}</p>${src(a.source)}</div>`).join('')||'<p class="scope-text">尚未找到唯一对应的申请记录。</p>'}</section>`;
    html+=`<section class="drawer-section"><h3>系统收入明细</h3>${r.systems.length?`<table><thead><tr><th>游戏 / 月份</th><th class="money">开票金额</th><th>同步状态</th></tr></thead><tbody>${r.systems.map(s=>`<tr><td>${esc(s.game)}<div class="cell-sub">${s.month} · ${src(s.source)}</div></td><td class="money">${money(s.amountCents)}</td><td>${esc(s.syncStatus)}</td></tr>`).join('')}</tbody></table>`:'<p class="scope-text">当前尚未定位系统记录，不产生待同步操作。</p>'}
    ${r.status==='ready'?`<div class="actions"><button class="btn primary" data-decide="${r.localDone?'reset':'done'}">${r.localDone?'撤销本地完成':'我已在 UO 完成'}</button></div><p class="scope-text">只记录你的确认，UO实际状态以新的系统导出为准。</p>`:''}
    ${r.linkDecision?'<div class="actions"><button class="btn small" data-unlink="true">撤销账期对应确认</button></div>':''}</section>`;
  }else{
    html+=`<section class="drawer-section"><h3>银行原始依据</h3><div class="evidence-card"><p><strong>银行：</strong>${esc(r.bankName||'未提供')}</p><p><strong>交易标识：</strong>${esc(r.transactionId||'未提供')}</p><p><strong>摘要：</strong>${esc(r.summary||'未提供')}</p><p><strong>分类：</strong>${esc(r.category||'未提供')}</p>${src(r.source)}</div><p class="scope-text">${esc(r.reason)}</p></section>
    <section class="drawer-section"><h3>这笔是否写入回款表</h3><div class="actions"><button class="btn primary" data-decide="included" ${r.currency!=='CNY'||r.status==='included'?'disabled':''}>这笔写入回款表</button><button class="btn" data-decide="excluded" ${r.status==='excluded'?'disabled':''}>这笔不写入回款表</button>${r.decision?'<button class="text-btn" data-decide="reset">撤销人工确认</button>':''}</div><p class="scope-text">确认只作用于这一笔。之后重新生成回款Excel才会更新输出副本。</p></section>`;
  }
  $('#drawerBody').innerHTML=html;if(!$('#detail').open)$('#detail').showModal();
}
async function submitDecision(value,kind=null){const detail=state.detail;if(!detail)return;const r=(detail.kind==='income'?state.data.income.cases:state.data.receipts.rows).find(r=>r.id===detail.id);await perform(async()=>{state.data=await api(`/api/months/${state.month}/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:kind||detail.kind,item_id:r.id,revision:r.revision,value})});render();openDetail(r.id);toast(value==='reset'?'已撤销本批确认':'已保存到本地项目')})}
async function upload(e){e.preventDefault();const form=e.target,submit=form.querySelector('button');submit.disabled=true;await perform(async()=>{const data=new FormData(form),month=data.get('month');state.data=await api(`/api/months/${month}/sources`,{method:'POST',body:data});state.month=month;await refreshMonths();render();toast('资料已导入并检查')});submit.disabled=false}
async function refreshMonths(){state.months=(await api('/api/months')).months;$('#monthSelect').innerHTML=state.months.map(m=>`<option value="${m}">${monthLabel(m)}</option>`).join('')}
document.addEventListener('click',async e=>{const n=e.target.closest('[data-view],[data-action],[data-filter],[data-detail],[data-decide],[data-remove],[data-candidate],[data-unlink]');if(!n)return;
  if(n.dataset.view)return navigate(n.dataset.view);
  if(n.dataset.detail)return openDetail(n.dataset.detail);
  if(n.dataset.decide)return submitDecision(n.dataset.decide);
  if(n.dataset.candidate)return submitDecision(n.dataset.candidate,'income_link');
  if(n.dataset.unlink)return submitDecision('reset','income_link');
  if(n.dataset.filter){state[state.view==='income'?'incomeFilter':'receiptFilter']=n.dataset.filter;state.page=1;render();return}
  if(n.dataset.remove)return perform(async()=>{state.data=await api(`/api/months/${state.month}/sources/${n.dataset.remove}`,{method:'DELETE'});render();toast('已移出本月，原始文件仍保留')});
  const action=n.dataset.action;
  if(titles[action])return navigate(action);
  if(action==='prev'||action==='next'){state.page+=action==='prev'?-1:1;return tableRender()}
  if(action==='run'){n.disabled=true;const ok=await load();n.disabled=false;if(ok)toast('已重新检查，重复资料不会再次计入');return}
  if(action==='july'){state.view='income';return load('2026-07')}
  if(action?.startsWith('export-')){n.disabled=true;n.textContent='正在生成…';await perform(async()=>{const kind=action.slice(7),result=await api(`/api/months/${state.month}/export/${kind}`,{method:'POST'});state.data=await api(`/api/months/${state.month}`);render();const a=document.createElement('a');a.href=result.url;a.download=result.name;document.body.append(a);a.click();a.remove();toast('Excel已生成，副本和处理记录已保存')});n.disabled=false;n.textContent=action==='export-income'?'生成收入 Excel':'生成回款 Excel'}
});
$('#closeDetail').addEventListener('click',()=>$('#detail').close());$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')&&e.clientX<$('#detail').getBoundingClientRect().left)$('#detail').close()});
$('#monthSelect').addEventListener('change',e=>{state.search='';state.entity='';load(e.target.value)});
perform(async()=>{await refreshMonths();const params=new URLSearchParams(location.search);state.view=titles[params.get('view')]?params.get('view'):'overview';await load(state.months.includes(params.get('month'))?params.get('month'):state.months[0])});
