import { createRequire } from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire('/Users/sato/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');
const {chromium}=require('playwright');
const dir=process.argv[2];await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8770/?month=2026-08');
await page.getByRole('heading',{name:'2026年8月 工作概览'}).waitFor();
await page.screenshot({path:dir+'/overview.png',fullPage:true});
assert(await page.getByText('44,182,604.85',{exact:false}).count());
await page.locator('[data-view="receipts"]').click();
await page.getByRole('heading',{name:'回款填写',exact:true}).waitFor();
await page.locator('[data-filter="pending"]').click();
await page.getByRole('searchbox').fill('585.80');
await page.getByRole('button',{name:'查看依据 →'}).click();
await page.getByRole('heading',{name:'深圳市腾讯计算机系统有限公司',exact:true}).waitFor();
await page.screenshot({path:dir+'/receipt-detail.png',fullPage:true});
assert(await page.getByText('FPP-',{exact:false}).count());
await page.getByRole('button',{name:'关闭详情'}).click();
await page.getByRole('searchbox').fill('');
await page.locator('[data-filter="included"]').click();
await page.screenshot({path:dir+'/receipts.png',fullPage:true});
await page.getByLabel('当前处理月份').selectOption('2026-07');
await page.locator('[data-view="income"]').click();
await page.getByText('53',{exact:false}).first().waitFor();
await page.screenshot({path:dir+'/income.png',fullPage:true});
await page.getByRole('searchbox').fill('2142');
await page.getByRole('button',{name:'查看依据 →'}).click();
await page.getByRole('button',{name:'我确认对应 2026-05'}).waitFor();
await page.screenshot({path:dir+'/income-detail.png',fullPage:true});
await page.getByRole('button',{name:'关闭详情'}).click();
await page.locator('[data-view="sources"]').click();
await page.getByRole('heading',{name:'添加本月或新月份资料'}).waitFor();
await page.screenshot({path:dir+'/sources.png',fullPage:true});
await page.reload();await page.getByRole('heading',{name:'添加本月或新月份资料'}).waitFor();
assert.equal(await page.getByLabel('当前处理月份').inputValue(),'2026-07');
await page.getByLabel('当前处理月份').selectOption('2026-08');await page.locator('[data-view="overview"]').click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:dir+'/mobile.png',fullPage:true});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
assert.deepEqual(errors,[]);
console.log(JSON.stringify({passed:true,errors,screenshots:7}));await browser.close();
